### ISSUE TITLE
Converting circular structure to JSON -> After update to SysAp 3.2.2

### ISSUE THREAD

**Issue by esusxunil** [mobilutz/ioBroker.freeathome#676]
**Describe the bug**  
I updated SysAp to Version 3.2.2, first, everything worked perfectly, but after a restart of ioBroker, the freeatHome Adapter didn't start anymore. I found the message "Converting circular structure to JSON " in the Logs. I updated the Adapter to the latest Version 0.0.20 with the same result, also stopping and starting the adapter led to the same result.

**To Reproduce**  
Start Adapter

**Expected behavior**  
Start of Adapter

**Screenshots & Logfiles**  
Converting circular structure to JSON --> starting at object with constructor 'Element' | property 'children' -> object with constructor 'Array' | index 0 -> object with constructor 'Element' --- property 'parent' closes the circle

TypeError: Converting circular structure to JSON --> starting at object with constructor 'Element' | property 'children' -> object with constructor 'Array' | index 0 -> object with constructor 'Element' --- property 'parent' closes the circle at JSON.stringify (<anonymous>) at FreeAtHomeApi.broadcastMessage (/opt/iobroker/node_modules/iobroker.freeathome/lib/freeathome.js:203:60) at Client.<anonymous> (/opt/iobroker/node_modules/freeathome-api/dist/lib/SystemAccessPoint.js:92:29) at Client.emit (node:events:525:35) at /opt/iobroker/node_modules/@xmpp/middleware/index.js:19:30 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

unhandled promise rejection: Converting circular structure to JSON --> starting at object with constructor 'Element' | property 'children' -> object with constructor 'Array' | index 0 -> object with constructor 'Element' --- property 'parent' closes the circle

Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Versions:**  
 - Adapter version: 0.0.20
 - JS-Controller version: 4.0.24
 - Node version: 18.16.0
 - Operating system: Linux in Docker Container (Buanet)

**Additional context**

**Comment by Kystim** [comment]
Same error here, after update Adapter from 0.0.13 to 0.0.20
